common:
  random_seed: 0
  input_channel_num: 3
  output_class_num: 10
  dataset: cifar10
  num_supervised: 10
moco:
  batch_size: 200
  queue_size: 10000
train:
  num_batch_in_epoch: 250
  num_labeled_batch: 2
  patience: 20
  lr: 0.0001 #学習率
  bw: 0.1
loss:
  sst: true
  ce: false
  hoffer: false
model:
  input_size: {height: 32, width: 32}
  feat_dim: 100
